spring.application.name=practiceProject

spring.datasource.url=jdbc:mysql://localhost:3306/practiceProject
spring.datasource.username=practice_project
spring.datasource.password=abcD123.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=1234